// in the future, this will be autogenerated

export type YAMLResume = {
    projects: Array<{
        name: string,
        description: string,
        languages_and_tools: string
    }>,
    work_experience: Array<{
        company: string,
        company_description: string,
        description: string
    }>
}