// in the future, this will be autogenerated

export type Project = {
    name: string,
    description: string,
    languages_and_tools: string
}
export type WorkExperience = {
    company: string,
    company_description: string,
    description: string
}

export type YAMLResume = {
    projects: Array<Project>,
    work_experience: Array<WorkExperience>
}